### ISSUE TITLE
Consider Making Build Into Library

### ISSUE THREAD

**Issue by caseysmithrc** [GhostPack/Rubeus#13]
So, couple ideas here, by passing parameters on cmdline, you expose sensitive material to Command Line Loggers.  

By being a library/dll assembly, you can import and load into other tools and remove any cmdline leaking.

Just an idea ;-) . Great work!

**Comment by HarmJ0y** [comment]
So this is quite easy to do, due to how .NET assemblies are built.

**Project** -> **Rubeus Properties** -> change **Output type** to **Class Library**. Compile, and add the Rubeus.dll as a reference to whatever project you want. Rubeus functionality can then be invoked:

```
// pass the Main method the arguments you want
Rubeus.Program.Main("dump /luid:3050142".Split());

// or invoke specific functionality manually
Rubeus.LSA.ListKerberosTicketDataAllUsers(new Rubeus.Interop.LUID());
```

You can use [ILMerge](https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=17630) to merge the Rubeus.dll into your resulting project assembly for a single, self-contained file.

I'll add these instructions as a note in the README.md.

**Comment by HarmJ0y** [comment]
Instructions are now in the README.md file https://github.com/GhostPack/Rubeus/blob/master/README.md#sidenote-building-rubeus-as-a-library
