### ISSUE TITLE
Can't figure out if Rubeus golden attacks work on non-domain-joined PCs

### ISSUE THREAD

**Issue by rick-engle** [GhostPack/Rubeus#150]
I can get this command to successfully execute a golden ticket attack on a patched Windows Server 2012 R2 DC from a Windows 10 PC that is domain joined and logged in with a standard domain user:
Rubeus golden /newpac /rc4:krbtgthash /ldap /user:domainuser2 /groups:512 /endtime:10y /ptt

But I can't figure out if it's possible to execute a similar attack on a non-domain-joined PC with a local admin account.   I tried with a syntax like this:
Rubeus golden /newpac /rc4:krbtgthash /sid:domainSID /user:mydomain\domainuser2 /groups:512 /endtime:10y /ptt
That does generate a ticket but if I try and use it, the ticket is immediately revoked, and I get a System Event ID 38 on the DC as the attack is seen and prevented.
Is there a way around this or is the only successful attack one that is made from a domain-joined PC?

Thanks.

**Comment by 0xe7** [comment]
For the `/user` argument I didn't think we supported the `domain\user` format but more importantly it looks like you aren't including the `/id` to provide the users valid RID, without that it will use the default value of 500 which will fail due to the RequestorSID PAC INFO BUFFER.

FWIW you can perform `/ldap` from a non-domain joined box (providing it has line of sight to a DC) by running in a shell that has domain credentials

**Comment by rick-engle** [comment]
Those are fantastic tips @0xe7 and resulted in me finding two golden ticket attacks that work on domain joined PCs!  I wrote up what was needed below but had another question.  Can any of these attacks be done using a non-existent user instead of an existing domain user?  I've seen that capability available in Mimikatz.

Non-domain-joined Golden ticket attacks that work:

Attack PC:  Non-domain-joined Windows 10 PC with line of sight to the DC
DC:  Windows Server 2012 R2 – Updates turned off but still has the updates that do PAC enforcement.

Attack #1:
Attack from a standard cmd.exe window running non-elevated:

Rubeus golden /newpac / rc4:krbtgtNTLMhash /user: domainusertoimpersonate /domain:yourdomain /sid:domainSID /id:RIDforDomainusertoimpersonate /groups:512 /endtime:10y /ptt

Attack #2:
Attack from a cmd.exe window using RunAs with a non-domain AD user:

Prep:
Use Windows+R to get to the Windows Run box then use this command:

runas /user:domain\domainuser "C:\Windows\System32\cmd.exe"
Cmd.exe window will come up and then type that user’s password.

NOTE:  I have found that the domain user that you use to get the domain context using the RunAs should be different from the impersonated domain name that is used in the Rubeus golden ticket attack.

Check out your user identity with whoami:

C:\Windows\System32>whoami
domian\domainuser

You are running in the context of a domain user, even though this is a rogue PC that is not domain-joined!

Rubeus golden /newpac /rc4:krbtgtNTLMhash /ldap /user:domainusertoimpersonate /groups:512 /endtime:10y /ptt

**Comment by 0xe7** [comment]
Golden tickets for a non-existent user no longer work against DC's patched against CVE-2021-42287 regardless of the tool you use to create them. You can create a golden ticket containing whatever username you want using Rubeus but the patch status of the DC will determine whether or not the TGT will be usable.

Also, FWIW, the `/newpac` switch is no longer required since PR #143 which made that behavior default and added the `/oldpac` switch to support the old behavior.
