### ISSUE TITLE
Wrong format for AES-encrypted tgsrep?

### ISSUE THREAD

**Issue by IISResetMe** [GhostPack/Rubeus#35]
Doing:
```
> rubeus.exe kerberoast /format:hashcat /aes
```
... produces AES256 hashes in the format:
```
$krb5tgs$18$*[username]$[domain]$[spn]*$[checksum]$[edata]
```

Feeding this to hashcat (v5.1.0) results in an error:
```
~> hashcat -m 19700 -o cracked.txt -a 0 krb5tgs.txt password.txt

Hashfile 'krb5tgs.txt' on line 1 ($krb5t...3bc0e660c3164355a02806c3d248afc0): Separator unmatched
No hashes loaded.
```

Looking at [the corresponding hashcat module](https://github.com/hashcat/hashcat/blob/master/src/modules/module_19700.c#L138), the expected format is: 

```
$krb5tgs$18$[username]$[domain]$*[spn]*$[checksum]$[edata]
```

Manually updating the hash from Rubeus results in another error
```
~> hashcat -m 19700 -o cracked.txt -a 0 krb5tgs2.txt password.txt

Hashfile 'krb5tgs2.txt' on line 1 ($krb5t...3bc0e660c3164355a02806c3d248afc0): Token length exception
No hashes loaded.
```

Apparently hashcat expects the [`checksum` to be exactly 24 chars wide](https://github.com/hashcat/hashcat/blob/master/src/modules/module_19700.c#L166). 

Manually moving the `$` separator 8 chars up makes hashcat load the hash, but doesn't succeed in cracking it. I suspect we need to re-calculate the checksum over the [`cipherText`](https://github.com/GhostPack/Rubeus/blob/master/Rubeus/lib/Roast.cs#L740) part, but I'm a bit out of my depth here 😄

**Comment by adams-kro** [comment]
just encountered this cracking krb5tgs$18 hashes, did you get a walk around it.?

**Comment by tmsteen** [comment]
I am not sure if this is related, but I got this today.  Rubeus reports that the Suport ETypes is only`RC4_HMAC_DEFAULT` but then I get a Type 18 AES ticket in return. Running that hash through Hashcat gives the same error as above. Manually changing the type to `23` is accepted by Hashcat. In this case, it seems I should have gotten a type 23 ticket no matter what as AES is not a supported EType. 
![image](https://user-images.githubusercontent.com/8290250/77103609-4e91f300-69e0-11ea-8cec-d0ea5e678576.png)

Unfortunately, this is on a live engagement so I am not sure I will be able to validate if Hashcat is actually able to crack the hash.

**Comment by csandker** [comment]
Found the same behaviour in my lab today, has there been an update to this?

This is what i caught on a first glance:

<pre>
.\Rubeus.exe kerberoast /aes /tgtdeleg
[...]
[*] SamAccountName         : Kerb_AES256
[*] DistinguishedName      : CN=KerberosAES256,CN=Users,DC=MonkeyIsland,DC=local
[*] ServicePrincipalName   : DC01/Kerb_AES256.MonkeyIsland.local
[*] PwdLastSet             : 4/20/2020 1:01:43 PM
[*] Supported ETypes       : AES256_CTS_HMAC_SHA1_96
[*] Hash                   : $krb5tgs$18$*Kerb_AES256$LAB$DC01/Kerb_AES256.lab.local*                             $B96F53F64F2E0C9EDA39A05770B35B0D$A2FF.....
</pre>

Checking with wireshark i can confirm the enc-type is indeed type 18 (AES256).<br>

Throwing this in hashcat results in ```Hashfile 'krb_aes256.hash' on line 1 ($krb5t...03ADF39D291091FF91F4D85AF4B3A070): Separator unmatched```, which i believe is due to the asterix in the hash format (as also stated in https://github.com/GhostPack/Rubeus/pull/39).<br>
Removing them results in: ```Hashfile 'krb_aes256.hash' on line 1 ($krb5t...03ADF39D291091FF91F4D85AF4B3A070): Token length exception```, which i believe is due to the token following the username/realm (which in the example above starts with 'B96F'). From Rubeus this token is 32chars in length whereas the hashcat examples [here](https://hashcat.net/wiki/doku.php?id=example_hashes) expect a token with a length of 24chars.

**Comment by Lexus89** [comment]
Having the same issue. @tmsteen Did you manage to crack the hash by changing it to type 23?

**Comment by adams-kro** [comment]
For my case manually changing to type 23 didn't exactly do it,, and trying
to crack the type18s gave an error in hashcat.. However, going back to
rubeus, since the supported ETypes was rc4., adding a rc4opsec switch
returned type 23 hashes that were crackable the usual way

**Comment by iontodd** [comment]
@Lexus89 Does my linked pull request work? 

For type 23 the checksum is the first 32, while for AES the checksum is the last 24. These are 16 and 12 bytes respectively.

If you have an existing type 23, it is being treated as follows:
`$ [checksum (32)] $ [cipher_text]`
When it is actually 
`$ [first 16 chars of cipher_text] $ [rest of cipher_text] + [checksum (24)]`

Therefore you need to perform the following:

- Remove $ between beginning and middle of cipher_text
- Move checksum from end to start
- Add $ between checksum and cipher_text

You will then end up with the correct format 
`$ [checksum (24)] $ [first 16 chars of cipher_text + rest of cipher_text]`

This is now in the format Hashcat expects:
![image](https://user-images.githubusercontent.com/5908733/83967899-9df00d00-a8c5-11ea-918a-ad20918f4870.png)
Please excuse the typo in the comment, however, this is immaterial (https://github.com/hashcat/hashcat/blob/master/src/modules/module_19700.c)

The above already takes place in Impacket's GetUserSPNs if this explanation is confusing: https://github.com/SecureAuthCorp/impacket/blob/master/examples/GetUserSPNs.py#L194
