### ISSUE TITLE
Create tickets directly for golden/silver ticket attacks?

### ISSUE THREAD

**Issue by VbScrub** [GhostPack/Rubeus#51]
Forgive me if I'm missing something, but it doesn't look like its currently possible to create golden/silver tickets in Rubeus and I was just curious if this is something we can add or if it was intentionally not included? 

I know we can use `/asktgt` and `/asktgs` to request legitimate tickets from a DC, and we can use `/ptt` to cache those. But what about the silver ticket attack style that you can do in mimikatz and Impacket's ticketer.py, where you don't get the service ticket from a DC but instead create a fake one using the service account's password to encrypt it (and then `/ptt` to cache that). 

It seems like a lot of the ground work required for that has already been done in Rubeus, so I'm wondering if it was an intentional choice to leave it out or if its just a case of no one having chance to implement it yet? If it's the latter, I might have a go at it.

**Comment by leechristensen** [comment]
It's the latter - Rubeus doesn't have any built-in support right now for manipulating a ticket's PAC. PR's are welcome though!

**Comment by VbScrub** [comment]
@leechristensen ok cool, thanks for the info. PAC structure seems fairly well documented and can always just do what Impacket does and get a real TGS as a template then just modify the SID and group membership list. I'll see if I can start working on this soon

**Comment by HarmJ0y** [comment]
This is something we did look into in the past, but doing the PAC serialization stuff didn't see as easy as we thought in C#. I know there is some existing work done by Vincent at https://github.com/vletoux/MakeMeEnterpriseAdmin/blob/master/MakeMeEnterpriseAdmin.ps1 .

Overall however, my general feeling on it was since you can create golden/silver tickets using Mimikatz "offline" and then import via Rubeus on host, I didn't see a compelling reason to implement the ticket forgery logic.

**Comment by VbScrub** [comment]
Wow yeah that code does look _a lot_ more complex than I thought it would be. I can see why you didn't pursue that, especially given the alternatives like you said
