### ISSUE TITLE
Support for full path in /output

### ISSUE THREAD

**Issue by okazymyrov** [GhostPack/Rubeus#76]
As a user of Rubeus, I would like to be able to output tickets into folders defined by full path.

Ref: https://github.com/GhostPack/Rubeus/issues/63

The workaround given in  https://github.com/GhostPack/Rubeus/blob/afa7ca11a0695196781e920df047bd1951a6b47f/Rubeus/lib/Helpers.cs#L275-L283 is protection from user stupidity, which is (I hope) out of the original purpose of the tool.

**Comment by okazymyrov** [comment]
As a practical consideration, I would not want to have path restrictions (or find a more reliable filtering method).

**Comment by VbScrub** [comment]
Yeah this is a bit of a strange limitation and could be avoided by using `IO.Path.GetFileName` to only apply the sanitization to the file name. Also even stranger is that only some parts of Rubeus use this when outputting data to file. Kerberoasting for example does let you specify a full path as the `outfile` parameter because it doesn't use this `MakeValidFileName` function, but `asktgt` does use it so you can't specify a full path with that. I just tested changing the code in this function to allow it to support full file paths and `asktgt` still seems to work fine so I'll raise a PR for it
